# Generated by Django 3.1.6 on 2021-03-01 06:13

import blog.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=400)),
                ('blog', models.TextField()),
                ('image', models.ImageField(upload_to=blog.models.upload_image_path)),
                ('is_published', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
