# Generated by Django 3.1.6 on 2021-02-20 18:44

import base.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=400)),
                ('blog', models.TextField()),
                ('photo', models.ImageField(upload_to=base.models.upload_image_path)),
                ('is_published', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
