# Generated by Django 3.1.6 on 2021-02-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210221_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='photo',
            new_name='image',
        ),
    ]
