# Generated by Django 3.1.6 on 2021-02-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='text_lebel',
        ),
        migrations.AddField(
            model_name='choice',
            name='option1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='choice',
            name='option2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.CharField(default='', max_length=100),
        ),
    ]
