# Generated by Django 3.1.6 on 2021-03-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210228_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('user_name', models.CharField(max_length=100)),
                ('first_question', models.CharField(max_length=100)),
                ('first_answer', models.CharField(max_length=100)),
                ('second_question', models.CharField(max_length=100)),
                ('second_answer', models.CharField(max_length=100)),
                ('feedback_text', models.CharField(max_length=100)),
            ],
        ),
    ]
