# Generated by Django 3.1.7 on 2021-03-07 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20210308_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='next_review_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 19, 7, 14, 715143, tzinfo=utc)),
        ),
    ]
