# Generated by Django 3.1.7 on 2021-04-03 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210308_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='next_review_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 17, 2, 34, 928018, tzinfo=utc)),
        ),
    ]
