# Generated by Django 3.1.7 on 2021-04-06 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20210403_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='next_review_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 18, 32, 18, 415452, tzinfo=utc)),
        ),
    ]
